-- DROP TABLE INGENIO.TAMANOGRANODETALLE;
-- DROP TABLE INGENIO.TAMANOGRANO;

-- DROP TABLE INGENIO.CTO24HDETALLE;
-- DROP TABLE INGENIO.CTO24H;

-- HSQLDB
-- TRUNCATE SCHEMA INGENIO AND COMMIT;

-- PostgreSQL
--DROP SCHEMA contenedor CASCADE;

DROP TABLE contenedor.seco_detalle;
DROP TABLE contenedor.seco;
